### PR TITLE
switch to more portable 'usage' module

### PR DESCRIPTION
**Pull request by pfrazee**
This also reduces the stats collected to just what we need. Docs: https://github.com/arunoda/node-usage

### CODE REVIEW

**Comment by ralphtheninja** [comment]
:+1: Mind rebasing it on latest master?

**Comment by pfrazee** [comment]
sure thing

**Comment by pfrazee** [comment]
should be good to go

**Comment by ralphtheninja** [comment]
I checked out a metric2 branch to rebase it again :) It's on latest master now.

**Comment by ralphtheninja** [comment]
https://github.com/ralphtheninja/sbot-test-guard/commit/e5110470241e50ce62e3c5f68d509f2736ef9b1e

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ sbot-test-guard@3.0.0
```

**Comment by pfrazee** [comment]
:+1:

**Pull request closed without merging**
